import type { StorefrontBranding } from '#shared/types/branding'

export const defaultBranding: StorefrontBranding = {
  logo_url: null,
  favicon_url: null,
  hero_image_url: null,
  primary_color: '#2563eb',
  secondary_color: '#111827',
  accent_color: '#ff7a1a',
  font_family: 'Aptos',
  hero_title: 'Cuidado perto de você.',
  hero_subtitle: 'Medicamentos, higiene e bem-estar com entrega para a sua região.',
  featured_title: 'Ofertas para cuidar de você',
  show_newsletter: true,
  header_message: 'Economize tempo. Encontre tudo para o seu cuidado.',
  contact_phone: '(11) 3000-1234',
  service_hours: 'Atendimento diário',
  hero_eyebrow: 'Farmácia online',
  hero_cta_label: 'Ver ofertas',
  categories_title: 'Compre por necessidade',
  promo_primary_title: 'Essenciais para a rotina',
  promo_primary_text: 'Produtos que vale ter sempre por perto.',
  promo_secondary_title: 'Cuidado simples, todos os dias',
  promo_secondary_text: 'Encontre tudo em poucos cliques.',
  promo_tertiary_title: 'Ofertas que fazem sentido',
  promo_tertiary_text: 'Preços especiais na seleção da loja.',
  offers_callout_title: 'Descontos que fazem bem para o bolso.',
  offers_callout_text: 'Uma seleção especial para o seu cuidado diário.',
  popular_title: 'Mais procurados',
  newsletter_eyebrow: 'Novidades da loja',
  newsletter_title: 'Cuide da sua rotina sem sair de casa.',
  newsletter_text: 'Receba ofertas e informações úteis da nossa loja.',
  newsletter_button_label: 'Quero receber',
  footer_tagline: 'cuidado todos os dias',
  footer_description: 'Sua farmácia online para encontrar medicamentos, higiene e bem-estar em um só lugar.',
  version: null,
}
